# Do not keep production secrets in the repository,
# instead read values from the environment.
# see https://stackoverflow.com/questions/23180650/how-to-solve-error-missing-secret-key-base-for-production-environment-rai/26541742#26541742
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>